### ISSUE TITLE
GitHub官网存在更新

### ISSUE THREAD

**Issue by xfoxfu** [Harry-Chen/GitHub-Hook-Weibo#3]
根据GitHub官网的更新，现在Hook功能更加强大了。。。
觉得无法选择了。。。
请问根据你们的设置应该如何选择，，，此外希望进行更新。。。
![image](https://f.cloud.github.com/assets/3616727/2242775/c833bcce-9d0f-11e3-840c-6faef34dbcf0.png)

**Comment by xavieryao** [comment]
静待周末

发自我的 iPod

在 2014-2-24，12:54，"小傅Fox" notifications@github.com 写道：

**Comment by xfoxfu** [comment]
`Payload version` = `Form`

`Which events would you like to trigger this webhook?` = `Just the push event.`

写在这里让后来人看到。

**Comment by xavieryao** [comment]
顺便 我认为这个hook工具还不可用

发自我的 iPod

在 2014-2-24，12:54，"小傅Fox" notifications@github.com 写道：

**Comment by xfoxfu** [comment]
提示：貌似说错了- -
`Payload version`应该选择`Form`！！！原来的comment已经修改。

**Comment by Harry-Chen** [comment]
GitHub这么一来看来任重道远啊。
顺便，现在我夜自修了每天都没时间>_<
@xavieryao

**Comment by xfoxfu** [comment]
= =你高几？看来学习还是最大冲突啊= =反正我这半年是完全闲着想干啥干啥了= =所以我开了个项目：coderfox/GitHub_Hook同时维护多个开源项目好闹心Linus真是有奉献精神！

**Comment by Harry-Chen** [comment]
高一。不是和学习冲突的问题。夜自修是迫不得已的选择。

------------------ 原始邮件 ------------------
发件人: "小傅Fox";notifications@github.com;
发送时间: 2014年3月2日(星期天) 上午10:41
收件人: "Harry-Chen/GitHub-Hook-Weibo"GitHub-Hook-Weibo@noreply.github.com; 
抄送: "Harry Chen"373685963@qq.com; 
主题: Re: [GitHub-Hook-Weibo] GitHub官网存在更新 (#3)

= =你高几？看来学习还是最大冲突啊= =反正我这半年是完全闲着想干啥干啥了==所以我开了个项目：coderfox/GitHub_Hook同时维护多个开源项目好闹心Linus真是有奉献精神！
